### ISSUE TITLE
Timed garbage collection

### ISSUE THREAD

**Issue by parikshit223933** [resque/resque-pool#229]
Currently resque pool forks n worker processes and by default those worker processes fork for each job.
For those who are using FORK_PER_JOB = false as an environment variable which disables forking the worker process when a new job is picked up, there can be significant memory issues because garbage collection does not run by default in ruby when a process is not exited.
Is it possible to provide a flag in cli to mention garbage collection time? (GC.start) 
Garbage collection will be running in a loop with a sleep interval of opts[:garbage_collection_duration] and will end as soon as the master pool process is exited.

**Comment by nevans** [comment]
GC _does_ run in ruby, so most likely what you're seeing is memory fragmentation over time.  Basically, memory can't be released back to the OS until every single object in that page of memory is freed, and you wind up with "holes" in the process's memory.  Since 2.6 or 2.7, ruby has had the ability to compact, but it isn't enabled by default: it can slow things down a little bit, it isn't supported by every C extension and some C extensions that do "support" it have had _weird_ errors (or just segfaults).

So, you could enable autocompaction or you could register a hook that ran after each job completes to run `GC.compact` manually.  That still won't get you quite as much memory back as just restarting the process.

But what I've been wanting to do for a while (when I have time) is merge this project with the functionality https://github.com/stulentsev/resque-multi-job-forks.  Until then, you can use both together, and `resque-multi-job-forks` will handle what you're looking for, I think.
